### ISSUE TITLE
Error: geom_waffle requires the following missing aesthetics: x and y

### ISSUE THREAD

**Issue by Rahulvks** [jennschilling/mylifeinmonths#1] opened 2021-10-16 06:36 UTC
Hi thanks for the script its interesting. when i re-produce the same code i am getting the below
Error `"Error: geom_waffle requires the following missing aesthetics: x and y"`

**Comment by jennschilling** [comment] 2021-10-20 01:35
Hello!
I experienced a different error when I ran the code today; it was related to one of the role annotations, and I have now fixed it. 
Without more information, I'm not sure exactly why you are getting that error. I did find this [thread on reddit](https://www.reddit.com/r/rstats/comments/i46xpt/issue_with_geom_waffle_aesthetics/) that recommends installing the development version of the waffle package, so perhaps you could try that. 
You could also look at the original version of the code from [Sharla Gelfand](https://github.com/sharlagelfand/mylifeinmonths).
Unfortunately, I'm not able to reproduce your error.
All the best,
Jenn

**Closed as completed** 2022-04-16 00:08 UTC
